import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";

const About = () => {
  return (
    <>
      <Head>
        <title>STREAM@S</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-4 max-w-2xl">
        <Header />
        <h2 className="text-2xl font-bold">STREAM@Sとは？</h2>
        <p className="my-2">
          2022年11月より順次、アイドルマスターシリーズの楽曲がストリーミングサービスで聴けるようになりました。このWebアプリケーションは、Spotify,
          Apple Music, Prime
          Musicの主要3プラットフォーム上でアイドルマスターシリーズの楽曲を見つけやすくし、皆様のプロデュース活動のお役に立てていただくことを目的としています。
        </p>
        <h2 className="text-2xl font-bold">既知の問題、仕様</h2>
        <ul>
          <li className="list-disc list-inside my-2">
            Firefoxで強化型トラッキング保護を厳格モードに設定していると、Prime
            Musicの埋め込みが表示されません。
          </li>
        </ul>
        <h2 className="text-2xl font-bold">誰が運営しているの？</h2>
        <p className="my-2">
          <Link
            href="https://lon.sagisawa.me"
            target="_blank"
            className="underline"
          >
            鷺沢ろん
          </Link>
          が設置、運営しております。
        </p>
        <h2 className="text-2xl font-bold">ソースコードはある？貢献できる？</h2>
        <p className="my-2">
          フロントエンド、APIともにGitHubに設置しております。プルリクエスト、およびIssueによる貢献を歓迎しております。
        </p>
      </div>
    </>
  );
};

export default About;
