import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";

const ShinyColors = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>STREAM@S - 765PRO ALL STARS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand="allstars" />
      <h2 className="text-xl font-bold">LIVE THE@TER COLLECTION</h2>
    </div>
  );
};

export default ShinyColors;
