import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";

const Info = () => {
  return (
    <>
      <Head>
        <title>STREAM@S</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-4 max-w-2xl">
        <Header />
        <h1 className="font-black text-3xl my-2">STREAM@Sからのお知らせ</h1>
        <article className="my-2">
          <div className="my-2">
            <h1 className="font-bold text-xl">
              765PRO ALLSTARSの楽曲を掲載しました
            </h1>
            <p className="text-sm">2023年1月5日</p>
          </div>
          <p>
            <Link href="/allstars" className="underline">
              765PRO ALLSTARSの楽曲掲載を開始いたしました。
            </Link>
            「ぷちます！」シリーズの楽曲は、後日掲載予定です。
          </p>
        </article>
        <article className="my-2">
          <div className="my-2">
            <h1 className="font-bold text-xl">
              vα-liv所属バーチャルライバーの楽曲の取り扱いについて
            </h1>
            <p className="text-sm">2022年12月28日</p>
          </div>
          <p>
            STREAM@Sでは、vα-liv所属バーチャルライバーの歌唱楽曲を取り扱う予定は現時点ではございません。
            <br />
            バーチャルライバー界隈にはキャラクターコンテンツとは異なる独自の文化が発達しており、このサービスで扱うには適切ではないと考えております。なおバーチャルライバー界隈の方がSTREAM@Sのコードをフォークし、独自に保守を行っていただくことは自由に行っていただけます(それを許容するライセンス設定としています)。
          </p>
        </article>
      </div>
    </>
  );
};

export default Info;
