import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";

const MillionLive = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>STREAM@S - Million Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand="millionlive" />
      <h1 className="text-2xl font-bold">LIVE THE@TER</h1>
      <h2 className="text-xl font-bold">LIVE THE@TER PERFORMANCE</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER HARMONY</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER DREAMERS</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER FORWARD</h2>

      <h1 className="text-2xl font-bold">THE@TER DAYS</h1>
      <h2 className="text-xl font-bold">MILLION THE@TER GENERATION</h2>
      <h2 className="text-xl font-bold">MILLION THE@TER WAVE</h2>
      <h2 className="text-xl font-bold">MILLION THE@TER SEASON</h2>
      <h2 className="text-xl font-bold">MILLION THE@TER VARIETY</h2>

      <h1 className="text-2xl font-bold">M@STER SPARKLE</h1>
      <h2 className="text-xl font-bold">M@STER SPARKLE</h2>
      <h2 className="text-xl font-bold">M@STER SPARKLE2</h2>

      <h1 className="text-2xl font-bold">THE@TER A/B/C</h1>
      <h2 className="text-xl font-bold">THE@TER ACTIVITIES</h2>
      <h2 className="text-xl font-bold">THE@TER BOOST</h2>
      <h2 className="text-xl font-bold">THE@TER CHALLENGE</h2>

      <h1 className="text-2xl font-bold">MILLION WORLD</h1>
      <h2 className="text-xl font-bold">MILLION RADIO</h2>
      <h2 className="text-xl font-bold">OTHER</h2>
    </div>
  );
};

export default MillionLive;
