import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";

const MillionLive = () => {
  return (
    <div className="container mx-auto px-4 max-w-2xl">
      <Head>
        <title>STREAM@S - Million Live</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand="millionlive" />
      <p>
        おしらせ:{" "}
        <a
          href="https://www.lantis.jp/news.php?id=1671786192"
          target="_blank"
          rel="noreferrer"
          className="underline hover:text-yellow-500 transition"
        >
          現在ミリオンライブの楽曲はプラットフォームによって配信状況が異なります。
        </a>
        <br />
        Lantis側での配信開始の告知が行われ次第、全楽曲・3プラットフォームでの掲載を行います。
        <br />
        また現時点で掲載されている楽曲はごく一部となります。順次楽曲データの拡充・掲載を進めてまいります。
      </p>
      <h1 className="text-2xl font-bold">LIVE THE@TER</h1>
      <h2 className="text-xl font-bold">LIVE THE@TER PERFORMANCE</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER HARMONY</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER DREAMERS</h2>
      <h2 className="text-xl font-bold">LIVE THE@TER FORWARD</h2>

      <h1 className="text-2xl font-bold">THE@TER DAYS</h1>
      <h2 className="text-xl font-bold">MILLION THE@TER GENERATION</h2>
      <h2 className="text-xl font-bold">MILLION THE@TER WAVE</h2>
      <ul>
        <li>
          <Link
            href="/album/lacm-14891"
            className="underline hover:text-yellow-500 transition"
          >
            01 Flyers!!!
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14892"
            className="underline hover:text-yellow-500 transition"
          >
            02 Chrono-Lexica
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14893"
            className="underline hover:text-yellow-500 transition"
          >
            03 Xs
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14894"
            className="underline hover:text-yellow-500 transition"
          >
            04 Sherry&apos;n Cherry
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14895"
            className="underline hover:text-yellow-500 transition"
          >
            05 ARCANA
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14896"
            className="underline hover:text-yellow-500 transition"
          >
            06 花咲夜
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14897"
            className="underline hover:text-yellow-500 transition"
          >
            07 Jus-2-Mint
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14898"
            className="underline hover:text-yellow-500 transition"
          >
            08 miraclesonic★expassion
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14899"
            className="underline hover:text-yellow-500 transition"
          >
            09 Fleuranges
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14900"
            className="underline hover:text-yellow-500 transition"
          >
            10 Glow Map
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14901"
            className="underline hover:text-yellow-500 transition"
          >
            11 オペラセリア・煌輝座
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14902"
            className="underline hover:text-yellow-500 transition"
          >
            12 ダイヤモンドダイバー◇
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14903"
            className="underline hover:text-yellow-500 transition"
          >
            13 TIntMe!
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14904"
            className="underline hover:text-yellow-500 transition"
          >
            14 TRICK&amp;TREAT
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14905"
            className="underline hover:text-yellow-500 transition"
          >
            15 chicAAmor
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-24106"
            className="underline hover:text-yellow-500 transition"
          >
            16 ≡君彩≡
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-24107"
            className="underline hover:text-yellow-500 transition"
          >
            17 ARMooo
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-24108"
            className="underline hover:text-yellow-500 transition"
          >
            18 ストロベリーポップムーン
          </Link>
        </li>
      </ul>
      <h2 className="text-xl font-bold">MILLION THE@TER SEASON</h2>
      <h2 className="text-xl font-bold">MILLION THE@TER VARIETY</h2>

      <h1 className="text-2xl font-bold">M@STER SPARKLE</h1>
      <h2 className="text-xl font-bold">M@STER SPARKLE</h2>
      <h2 className="text-xl font-bold">M@STER SPARKLE2</h2>

      <h1 className="text-2xl font-bold">THE@TER A/B/C</h1>
      <h2 className="text-xl font-bold">THE@TER ACTIVITIES</h2>
      <h2 className="text-xl font-bold">THE@TER BOOST</h2>
      <h2 className="text-xl font-bold">THE@TER CHALLENGE</h2>

      <h1 className="text-2xl font-bold">OTHER</h1>
      <h2 className="text-xl font-bold">MILLION RADIO</h2>
      <ul>
        <li>
          <Link
            href="/album/lacm-14234"
            className="underline hover:text-yellow-500 transition"
          >
            U・N・M・E・I ライブ
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14506"
            className="underline hover:text-yellow-500 transition"
          >
            ターンオンタイム！
          </Link>
        </li>
        <li>
          <Link
            href="/album/lacm-14961"
            className="underline hover:text-yellow-500 transition"
          >
            ENDLESS TOUR
          </Link>
        </li>
      </ul>
      <h2 className="text-xl font-bold">OTHER</h2>
    </div>
  );
};

export default MillionLive;
