import Header from "../components/header";
import Head from "next/head";
import Link from "next/link";
import List from "../components/list";
import tailwindcssConfig from "../tailwind.config";
import { Album, Albums } from "../types/Album";

const API_ENDPOINT =
  process.env.API_ENDPOINT || "https://stream-api.kitahina.co";

export const getStaticProps = async () => {
  const albums: Albums = {};
  await fetch(`${API_ENDPOINT}/album/sidem`)
    .then((response) => {
      return response.json();
    })
    .then((json) => {
      return json.data;
    })
    .then((data) => {
      if (data) {
        let series = "";
        data.forEach((album: Album) => {
          if (album.series && series !== album.series) {
            series = album.series;
          } else if (!album.series) {
            series = "OTHER";
          }

          const name = album["name"].match(/^(.+?\s)([01]\d)(.*)/);
          if (name && name[3].length > 0) {
            album["name"] = name[2] + name[3];
          }

          if (!albums[series]) {
            albums[series] = [];
          }

          albums[series].push(album);
        });
      }
    });
  await fetch(`${API_ENDPOINT}/album/moiw2023`)
    .then((response) => {
      return response.json();
    })
    .then((json) => {
      return json.data;
    })
    .then((data) => {
      if (albums["OTHER"] && data) {
        albums["OTHER"].push(data);
      }
    });

  return {
    props: { albums },
  };
};

const SideM = ({ albums }: { albums: Albums }) => {
  return (
    <div
      className="container mx-auto px-4 max-w-2xl"
      style={{
        ["--color-brand" as any]:
          tailwindcssConfig.theme?.extend.colors.brand["sidem"].DEFAULT,
      }}
    >
      <Head>
        <title>STREAM@S - SideM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand="sidem" />
      <List albums={albums} />
    </div>
  );
};

export default SideM;
